project_name: above_shrubs
experiment_type: 'chm'
experiment_name: '${project_name}-${experiment_type}'
model_name: custom_unet
version: 1.1.1
main_dir: /explore/nobackup/projects/above/misc/ABoVE_Shrubs/development

#------------------------------------- Setup -------------------------------------#

# Here we go from tif's to .npy's for training

# directory that store train data
train_data_dir:  /explore/nobackup/people/mmacande/srlite/chm_model/20231014_chm/train_merged_nodtm_images
train_label_dir: /explore/nobackup/people/mmacande/srlite/chm_model/20231014_chm/train_merged_chm
train_tiles_dir:  '/explore/nobackup/people/mmacande/srlite/chm_model/20231014_chm/train_merged_nodtm_npy'

# directory that stores test data
test_data_dir:  /explore/nobackup/people/mmacande/srlite/chm_model/20231014_chm/test_merged_nodtm_images
test_label_dir: /explore/nobackup/people/mmacande/srlite/chm_model/20231014_chm/test_merged_chm
test_tiles_dir: '/explore/nobackup/people/mmacande/srlite/chm_model/20231014_chm/test_merged_nodtm_npy'

batch_size: 512

#------------------------------------- General -------------------------------------#

model_dir: '${main_dir}/models/${model_name}/${version}'

seed: 43
gpu_devices: 0,1,2,3
mixed_precision: False
xla: False

input_bands:
  - B
  - G
  - R
  - NIR

output_bands:
  - B
  - G
  - R
  - NIR
  
#substract_labels: True
normalize: 1.0
normalize_label: 1.0

expand_dims: True
tile_size: 64
include_classes: False

# 90/180 degree rotations not appropriate in Arctic,
# could use smaller/jittered augmentation instead
augment: False

# standardization functions: local, global, mixed
standardization: 'global'
#batch_size: 32
n_classes: 1
test_size: 0.10
learning_rate: 0.00001
max_epochs: 6000
patience: 10

model: 'tfc.model.networks.regression.regression_unet.unet_batchnorm_regression(nclass=1, input_size=(64, 64, 4), maps=[64, 128, 256, 512, 1024],final_activation="linear")'

loss: 'tf.keras.losses.MeanAbsoluteError()'

optimizer: tf.keras.optimizers.Adam

metrics:
  - 'tf.keras.metrics.MeanSquaredError()'
  - 'tf.keras.metrics.RootMeanSquaredError()'
  - 'tf.keras.metrics.MeanAbsoluteError()'
  - 'tfa.metrics.RSquare()'

callbacks:
  - "tf.keras.callbacks.ModelCheckpoint(save_best_only=True, mode='min', monitor='val_loss', filepath='${model_dir}/{epoch:03d}-{val_loss:.2f}.hdf5')"
  - "tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=5)"
  - "tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=False)"
  - "tf.keras.callbacks.TerminateOnNaN()"
  - "tf.keras.callbacks.CSVLogger('${model_dir}/${experiment_name}.csv')"
  - "tf.keras.callbacks.BackupAndRestore('${model_dir}/backup')"

#------------------------------------- Inference -------------------------------------#

window_size: 10000
pred_batch_size: 64
inference_overlap: 0.50
inference_treshold: 0.50
prediction_dtype: float32
prediction_nodata: -9999

cloudmask_path: '/explore/nobackup/projects/ilab/test/vhr-cloudmask/*/*'

inference_regex_list:
  - '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite/002m/WV03_20200704_M1BS_104001005EADB900-sr-02m.tif'
  - '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite/002m/WV02_20200722_M1BS_10300100AB1FD100-sr-02m.tif'
  - '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite/002m/WV03_20190822_M1BS_104001005054F700-sr-02m.tif'
  - '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite/002m/WV03_20170719_M1BS_104001002F7A2E00-sr-02m.tif'
  - '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite/002m/WV02_20160817_M1BS_103001005B484100-sr-02m.tif'
  - '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite/002m/WV02_20190820_M1BS_1030010099BF2F00-sr-02m.tif'
  - '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite/002m/WV02_20110727_M1BS_103001000D914900-sr-02m.tif'
  - '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite/002m/WV02_20190820_M1BS_10300100968FB300-sr-02m.tif'
  - '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite/002m/WV02_20190820_M1BS_10300100954DE000-sr-02m.tif'
  - '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite/002m/WV02_20120721_M1BS_103001001AB23900-sr-02m.tif'
  #- '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/srlite_ak_2024/*_sr_02m.tif'
  #- '/explore/nobackup/projects/ilab/data/srlite/products/srlite-0.9.15-10282022-qa/10282022-all/Siberia/*.tif'
  #- '/explore/nobackup/projects/above/misc/ABoVE_Shrubs/footprints/fullpaths_srlite_chm_priority.csv'

inference_save_dir: '${main_dir}/${experiment_type}/${model_name}/${version}'